script: |
  cd /home/ec2-user/Inventory_System

  git reset --hard HEAD
  git clean -fd
  git pull origin main

  cd backend
  npm install

  cd ../frontend
  rm -rf dist
  npm install
  npm run build